services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes: [ ] # Disabling persistence
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    external: true