services:
  client:
    container_name: client
    build:
      context: ../frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:80"
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ../backend:/var/www/backend
      - ../backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network

networks:
  app-network:
    external: true