services:
  server:
    container_name: server
    build:
      context: ../backend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../backend:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes: [ ] # Disabling persistence
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 2048mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  db_data: